### PR TITLE
Support parsing element metadata and support history files

### PR DESCRIPTION
**Pull request by aleung**

### CODE REVIEW

**Comment by thomersch** [comment]
Thanks for contributing, I think it would be nice to have that functionality. Unfortunately it changes handling of every object thus creating a slowdown of about 10–15% (measured using the included benchmarks). I think particularly, the Info struct which is referenced by pointer adds a lot of pressure onto the garbage collector.

Because most people do not process meta data and e.g. the Geofabrik extracts don't even include user data, maybe it would be better to have a separate API for this? Or maybe we could introduce a build flag that enables meta data?

**Comment by aleung** [comment]
@thomersch Thanks for reviewing. Let me check how to make the meta data feature selective.

**Comment by aleung** [comment]
I added a new API `NewFullDecoder` to retrieve a decoder with capability to decode optional meta data. I hesitate if it is a good name and you might have better suggestion.

I have also done some benchmark tests. But in my test the cases using built-in data didn't show significant performance downgrade even if using my previous commit. The worse one has slowdown 3.3%.

I used a 769MB history file china-internal.osh.pbf which contains 86736868 nodes, 9359828 ways, 324865 relations in the complete file test. The file was downloaded from Geofabrik with a login user. They had removed data file with metadata download for anonymous user because of European Union GDPR.  

Test shows that `NewFullDecoder` increases 11% processing time while `NewDecoder` increases just 1% which is within margin of test error.       

The benchmarks are recorded in this Excel sheet:
[benchmark.xlsx](https://github.com/thomersch/gosmparse/files/3077214/benchmark.xlsx)

**Comment by aleung** [comment]
@thomersch, I would like to hear your feedback. Don't know if you have a little time to review my update?

**Comment by thomersch** [comment]
I made a few changes and optimisations (e.g. native time.Time field instead of timestamp) as well as some naming and documentation improvements and merged the whole thing. Thanks for contributing!

If you have further suggestions, let me know.

**Pull request merged**
